#pragma once

#include <cstdint>

namespace Common
{
    struct Color {
        uint8_t r=0, g=0, b=0, a=0;

        Color() = default;
        Color( uint8_t r_, uint8_t g_, uint8_t b_, uint8_t a_=255) :
            r(r_), g(g_), b(b_), a(a_)
        {}

        friend Color operator * ( Color rhs, Color lhs )
        {
            return Color(
                (unsigned)rhs.r * (unsigned)lhs.r / 255u,
                (unsigned)rhs.g * (unsigned)lhs.g / 255u,
                (unsigned)rhs.b * (unsigned)lhs.b / 255u,
                (unsigned)rhs.a * (unsigned)lhs.a / 255u
            );
        }

        static Color FromHVS( uint8_t hue, uint8_t value, uint8_t saturation );
    };

    namespace NamedColors
    {
        extern const Color PreMulAlpha50,
                           PreMulAlpha100,
                           PreMulAlpha150,
                           PreMulAlpha200;

        // HTML color names, from: https://www.w3schools.com/colors/colors_names.asp
        extern const Color AliceBlue,
                           AntiqueWhite,
                           Aqua,
                           Aquamarine,
                           Azure,
                           Beige,
                           Bisque,
                           Black,
                           BlanchedAlmond,
                           Blue,
                           BlueViolet,
                           Brown,
                           BurlyWood,
                           CadetBlue,
                           Chartreuse,
                           Chocolate,
                           Coral,
                           CornflowerBlue,
                           Cornsilk,
                           Crimson,
                           Cyan,
                           DarkBlue,
                           DarkCyan,
                           DarkGoldenRod,
                           DarkGray,
                           DarkGrey,
                           DarkGreen,
                           DarkKhaki,
                           DarkMagenta,
                           DarkOliveGreen,
                           DarkOrange,
                           DarkOrchid,
                           DarkRed,
                           DarkSalmon,
                           DarkSeaGreen,
                           DarkSlateBlue,
                           DarkSlateGray,
                           DarkSlateGrey,
                           DarkTurquoise,
                           DarkViolet,
                           DeepPink,
                           DeepSkyBlue,
                           DimGray,
                           DimGrey,
                           DodgerBlue,
                           FireBrick,
                           FloralWhite,
                           ForestGreen,
                           Fuchsia,
                           Gainsboro,
                           GhostWhite,
                           Gold,
                           GoldenRod,
                           Gray,
                           Grey,
                           Green,
                           GreenYellow,
                           HoneyDew,
                           HotPink,
                           IndianRed,
                           Indigo,
                           Ivory,
                           Khaki,
                           Lavender,
                           LavenderBlush,
                           LawnGreen,
                           LemonChiffon,
                           LightBlue,
                           LightCoral,
                           LightCyan,
                           LightGoldenRodYellow,
                           LightGray,
                           LightGrey,
                           LightGreen,
                           LightPink,
                           LightSalmon,
                           LightSeaGreen,
                           LightSkyBlue,
                           LightSlateGray,
                           LightSlateGrey,
                           LightSteelBlue,
                           LightYellow,
                           Lime,
                           LimeGreen,
                           Linen,
                           Magenta,
                           Maroon,
                           MediumAquaMarine,
                           MediumBlue,
                           MediumOrchid,
                           MediumPurple,
                           MediumSeaGreen,
                           MediumSlateBlue,
                           MediumSpringGreen,
                           MediumTurquoise,
                           MediumVioletRed,
                           MidnightBlue,
                           MintCream,
                           MistyRose,
                           Moccasin,
                           NavajoWhite,
                           Navy,
                           OldLace,
                           Olive,
                           OliveDrab,
                           Orange,
                           OrangeRed,
                           Orchid,
                           PaleGoldenRod,
                           PaleGreen,
                           PaleTurquoise,
                           PaleVioletRed,
                           PapayaWhip,
                           PeachPuff,
                           Peru,
                           Pink,
                           Plum,
                           PowderBlue,
                           Purple,
                           RebeccaPurple,
                           Red,
                           RosyBrown,
                           RoyalBlue,
                           SaddleBrown,
                           Salmon,
                           SandyBrown,
                           SeaGreen,
                           SeaShell,
                           Sienna,
                           Silver,
                           SkyBlue,
                           SlateBlue,
                           SlateGray,
                           SlateGrey,
                           Snow,
                           SpringGreen,
                           SteelBlue,
                           Tan,
                           Teal,
                           Thistle,
                           Tomato,
                           Turquoise,
                           Violet,
                           Wheat,
                           White,
                           WhiteSmoke,
                           Yellow,
                           YellowGreen;
    }
}
